### ISSUE TITLE
Manual: Summarizing our discussions from this semester

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/sp19-516-135#7]
i will move your readme to cloudmesh manual so others can benefit from your work

i will update your readme once i am done. 

form than on update the documentation directly in cloudmesh-manual

**Comment by laszewsk** [comment]
I moved the documentation, and leveraged what you and I discussed throughout the semester putting it in a workfleo that can be replicated by the user this includes

The discussion we had atthe begining of the semester where we outlined we need

a) encrypting the yaml file
b) an easy whay for the user to do this from the commandlien
c) a way to easily modify values in the encrypted file

It also integrates your observation for large file encryptyion and a prvious idea you and me discussued in wich we suggested to just store the sectres in a file while all thos other things could be in an unencrypted file. The user can have the choice which one they like.

**Comment by xiaoyue10131748** [comment]
Thanks for all your kind help!

**Comment by laszewsk** [comment]
implementation of some of the features proposed in the document is missing. However we filed another issue to summarize the missing actions.
